cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'chruby'
brew 'coreutils'
brew 'grc'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-install'
brew 'roundup'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask 'google-chrome'
cask 'macpass'
cask 'slack'
